### ISSUE TITLE
Route de Bracieux, Chambord, not in the dataset (but housenumbers are)

### ISSUE THREAD

**Issue by yohanboniface** [etalab/ban-geocode#4]
7381134:410340020R-10|10|Route de Bracieux|41250|Chambord|CAD|47.611867|1.518545|Loir-et-Cher|Centre|number
7381135:410340020R-11|11|Route de Bracieux|41250|Chambord|CAD|47.611973|1.518691|Loir-et-Cher|Centre|number
7381136:410340020R-1|1|Route de Bracieux|41250|Chambord|CAD|47.611885|1.518991|Loir-et-Cher|Centre|number
7381137:410340020R-12|12|Route de Bracieux|41250|Chambord|CAD|47.612053|1.518886|Loir-et-Cher|Centre|number
7381138:410340020R-13|13|Route de Bracieux|41250|Chambord|CAD|47.611894|1.519056|Loir-et-Cher|Centre|number
7381139:410340020R-13B|13BIS|Route de Bracieux|41250|Chambord|CAD|47.611914|1.519037|Loir-et-Cher|Centre|number
7381140:410340020R-2|2|Route de Bracieux|41250|Chambord|CAD|47.611811|1.518810|Loir-et-Cher|Centre|number
7381141:410340020R-3|3|Route de Bracieux|41250|Chambord|CAD|47.611786|1.518776|Loir-et-Cher|Centre|number
7381142:410340020R-4|4|Route de Bracieux|41250|Chambord|CAD|47.611704|1.518579|Loir-et-Cher|Centre|number
7381143:410340020R-48|48|Route de Bracieux|41250|Chambord|CAD|47.612765|1.518971|Loir-et-Cher|Centre|number
7381144:410340020R-50|50|Route de Bracieux|41250|Chambord|CAD|47.612284|1.519929|Loir-et-Cher|Centre|number
7381145:410340020R-51|51|Route de Bracieux|41250|Chambord|CAD|47.612144|1.519884|Loir-et-Cher|Centre|number
7381146:410340020R-52|52|Route de Bracieux|41250|Chambord|CAD|47.611985|1.519908|Loir-et-Cher|Centre|number
7381147:410340020R-53|53|Route de Bracieux|41250|Chambord|CAD|47.611831|1.519901|Loir-et-Cher|Centre|number
7381148:410340020R-54|54|Route de Bracieux|41250|Chambord|CAD|47.611662|1.520081|Loir-et-Cher|Centre|number
7381149:410340020R-54A|54A|Route de Bracieux|41250|Chambord|CAD|47.611144|1.520137|Loir-et-Cher|Centre|number
7381150:410340020R-55|55|Route de Bracieux|41250|Chambord|CAD|47.609700|1.520501|Loir-et-Cher|Centre|number
7381151:410340020R-5|5|Route de Bracieux|41250|Chambord|CAD|47.611664|1.518571|Loir-et-Cher|Centre|number
7381152:410340020R-56|56|Route de Bracieux|41250|Chambord|CAD|47.609654|1.520706|Loir-et-Cher|Centre|number
7381153:410340020R-58|58|Route de Bracieux|41250|Chambord|CAD|47.612500|1.518846|Loir-et-Cher|Centre|number
7381154:410340020R-59|59|Route de Bracieux|41250|Chambord|CAD|47.612635|1.518795|Loir-et-Cher|Centre|number
7381155:410340020R-61|61|Route de Bracieux|41250|Chambord|CAD|47.612797|1.518364|Loir-et-Cher|Centre|number
7381156:410340020R-62|62|Route de Bracieux|41250|Chambord|CAD|47.612745|1.518567|Loir-et-Cher|Centre|number
7381157:410340020R-63|63|Route de Bracieux|41250|Chambord|CAD|47.612911|1.518282|Loir-et-Cher|Centre|number
7381158:410340020R-6|6|Route de Bracieux|41250|Chambord|CAD|47.611642|1.518299|Loir-et-Cher|Centre|number
7381159:410340020R-7|7|Route de Bracieux|41250|Chambord|CAD|47.611656|1.518245|Loir-et-Cher|Centre|number
7381160:410340020R-80|80|Route de Bracieux|41250|Chambord|CAD|47.583369|1.530664|Loir-et-Cher|Centre|number
7381161:410340020R-8|8|Route de Bracieux|41250|Chambord|CAD|47.611763|1.518255|Loir-et-Cher|Centre|number
7381162:410340020R-95|95|Route de Bracieux|41250|Chambord|CAD|47.612500|1.518859|Loir-et-Cher|Centre|number
7381163:410340020R-9|9|Route de Bracieux|41250|Chambord|CAD|47.611825|1.518407|Loir-et-Cher|Centre|number

**Comment by cquest** [comment]
Same as https://github.com/yohanboniface/bano-geocode/issues/3
