### ISSUE TITLE
Hauteluce, both village and commune

### ISSUE THREAD

**Issue by yohanboniface** [etalab/ban-geocode#5]
```
73132B063N||Hauteluce|73620|Hauteluce|OSM|45.750645|6.585376|Savoie|Rhône-Alpes|village
73132|||73620|Hauteluce|IGN|45.750573|6.584800|Savoie|Rhône-Alpes|commune
```

**Comment by cquest** [comment]
fixed !
If the place name is the same as the town name, only the second line will be un the full dump.

**Comment by yohanboniface** [comment]
Great! Do you think you will be able to dump a new full.csv on Monday, or we are stuck with osm105?
